"""
Decision skill.

This module assembles the invoice and contract evidence generated by
Snowflake and returns one structured decision package.

Snowflake SQL remains the primary source of truth for:

- anomaly detection
- severity classification
- recommended action
- contract status
- price comparison

The Python layer does not recreate those rules. It only applies explicit
fail-safe handling when contract evidence is missing or unusable.
"""

import json
import sys
from typing import Any

from contract_clause_skill import (
    get_contract_analysis,
    get_contract_status,
    get_price_check,
)
from invoice_anomaly_skill import (
    get_invoice_anomalies,
    get_review_queue_entry,
)


def _normalise_identifier(value: str, label: str) -> str:
    """
    Validate and normalise an invoice or vendor identifier.
    """
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"{label} cannot be empty.")

    return value.strip().upper()


def _get_recommended_action(
    review_entry: dict[str, Any],
) -> str:
    """
    Read the SQL-computed recommendation from AP_REVIEW_QUEUE.

    A few candidate names are supported so that a minor column-name
    difference does not require rewriting the decision workflow.
    """
    candidate_columns = (
        "RECOMMENDED_ACTION",
        "RECOMMENDATION",
        "DECISION",
        "ACTION",
    )

    for column_name in candidate_columns:
        value = review_entry.get(column_name)

        if value is not None and str(value).strip():
            return str(value).strip().upper()

    raise KeyError(
        "AP_REVIEW_QUEUE does not contain a recognised recommendation "
        "column. Expected one of: "
        + ", ".join(candidate_columns)
    )


def _get_severity(
    review_entry: dict[str, Any] | None,
    default: str,
) -> str:
    """
    Return the SQL-computed severity when available.
    """
    if review_entry is None:
        return default

    severity = review_entry.get("SEVERITY")

    if severity is None or not str(severity).strip():
        return default

    return str(severity).strip().upper()


def _build_reasoning_facts(
    review_entry: dict[str, Any] | None,
) -> dict[str, Any]:
    """
    Return the useful SQL evidence without repeating identifier fields.
    """
    if review_entry is None:
        return {}

    excluded_columns = {
        "INVOICE_ID",
        "VENDOR_ID",
    }

    return {
        key: value
        for key, value in review_entry.items()
        if key not in excluded_columns
    }


def decide(invoice_id: str, vendor_id: str) -> dict[str, Any]:
    """
    Assemble and return the final decision package.

    Returns a dictionary containing:

    - invoice_id
    - vendor_id
    - decision
    - severity
    - reasoning_facts
    - evidence
    """
    normalised_invoice_id = _normalise_identifier(
        invoice_id,
        "Invoice ID",
    )
    normalised_vendor_id = _normalise_identifier(
        vendor_id,
        "Vendor ID",
    )

    invoice_anomalies = get_invoice_anomalies(
        normalised_invoice_id
    )

    review_entry = get_review_queue_entry(
        normalised_invoice_id
    )

    contract_analysis = get_contract_analysis(
        normalised_vendor_id
    )

    contract_status = get_contract_status(
        normalised_vendor_id
    )

    price_check = get_price_check(
        normalised_vendor_id
    )

    evidence = {
        "invoice_anomalies": invoice_anomalies,
        "review_entry": review_entry,
        "contract_analysis": contract_analysis,
        "contract_status": contract_status,
        "price_check": price_check,
    }

    # Fail-safe branch: no usable contract evidence exists.
    if contract_analysis is None:
        return {
            "invoice_id": normalised_invoice_id,
            "vendor_id": normalised_vendor_id,
            "decision": "ESCALATE",
            "severity": "HIGH",
            "decision_source": "PYTHON_FAIL_SAFE",
            "reasoning_facts": {
                "no_contract_analysis_on_file": True,
                "message": (
                    "The invoice cannot be validated because no contract "
                    "analysis is available for the vendor."
                ),
            },
            "evidence": evidence,
        }

    # Fail-safe branch: contract record itself is missing.
    if contract_status is None:
        return {
            "invoice_id": normalised_invoice_id,
            "vendor_id": normalised_vendor_id,
            "decision": "ESCALATE",
            "severity": "HIGH",
            "decision_source": "PYTHON_FAIL_SAFE",
            "reasoning_facts": {
                "contract_status_missing": True,
                "message": (
                    "The vendor contract status could not be verified."
                ),
            },
            "evidence": evidence,
        }

    status_value = str(
        contract_status.get("CONTRACT_STATUS", "")
    ).strip().upper()

    # Fail-safe branch: an expired contract must not be approved.
    if status_value == "EXPIRED":
        return {
            "invoice_id": normalised_invoice_id,
            "vendor_id": normalised_vendor_id,
            "decision": "ESCALATE",
            "severity": "HIGH",
            "decision_source": "PYTHON_FAIL_SAFE",
            "reasoning_facts": {
                "contract_expired": True,
                "contract_end": contract_status.get(
                    "CONTRACT_END"
                ),
                "message": (
                    "The vendor contract is expired and requires "
                    "manual review."
                ),
            },
            "evidence": evidence,
        }

    # No review-queue record means the SQL workflow did not flag the invoice.
    if review_entry is None:
        return {
            "invoice_id": normalised_invoice_id,
            "vendor_id": normalised_vendor_id,
            "decision": "APPROVE",
            "severity": "LOW",
            "decision_source": "SQL_CLEAN_PATH",
            "reasoning_facts": {
                "clean_invoice": True,
                "message": (
                    "No AP review-queue entry was generated for this "
                    "invoice."
                ),
            },
            "evidence": evidence,
        }

    # Normal path: use Snowflake's precomputed recommendation directly.
    decision = _get_recommended_action(review_entry)
    severity = _get_severity(
        review_entry,
        default="MEDIUM",
    )

    return {
        "invoice_id": normalised_invoice_id,
        "vendor_id": normalised_vendor_id,
        "decision": decision,
        "severity": severity,
        "decision_source": "SNOWFLAKE_SQL",
        "reasoning_facts": _build_reasoning_facts(
            review_entry
        ),
        "evidence": evidence,
    }


def main() -> None:
    """
    Run a command-line test for one invoice and vendor.
    """
    if len(sys.argv) != 3:
        print(
            "Usage:\n"
            "  python decision_skill.py "
            "<INVOICE_ID> <VENDOR_ID>\n\n"
            "Example:\n"
            "  python decision_skill.py INV0007 V003"
        )
        raise SystemExit(1)

    try:
        result = decide(
            sys.argv[1],
            sys.argv[2],
        )

        print(
            json.dumps(
                result,
                indent=2,
                default=str,
            )
        )

    except ValueError as exc:
        print(f"Input error: {exc}")
        raise SystemExit(1)

    except Exception as exc:
        print("Failed to assemble the invoice decision.")
        print(exc)
        raise SystemExit(1)


if __name__ == "__main__":
    main()