USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS AP_AUTOPILOT_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE AP_AUTOPILOT_WH;

SHOW WAREHOUSES LIKE 'AP_AUTOPILOT_WH';