USE ROLE ACCOUNTADMIN;
USE WAREHOUSE AP_AUTOPILOT_WH;
USE DATABASE AP_AUTOPILOT;
USE SCHEMA CORE;

CREATE OR REPLACE TABLE CONTRACT_TEXT (
    FILE_NAME VARCHAR,
    VENDOR_ID VARCHAR,
    RAW_TEXT VARCHAR
);