USE ROLE ACCOUNTADMIN;
USE WAREHOUSE AP_AUTOPILOT_WH;
USE DATABASE AP_AUTOPILOT;
USE SCHEMA CORE;


CREATE OR REPLACE VIEW CONTRACT_SEARCH_VIEW AS
SELECT
    FILE_NAME,
    VENDOR_ID,
    RAW_TEXT,
    LOWER(RAW_TEXT) AS SEARCHABLE_TEXT
FROM CONTRACT_TEXT;


SELECT
    FILE_NAME,
    VENDOR_ID,
    CASE
        WHEN SEARCHABLE_TEXT LIKE '%automatic renew%'
          OR SEARCHABLE_TEXT LIKE '%automatically renew%'
        THEN TRUE
        ELSE FALSE
    END AS HAS_AUTOMATIC_RENEWAL,

    CASE
        WHEN SEARCHABLE_TEXT LIKE '%late payment%'
          OR SEARCHABLE_TEXT LIKE '%overdue balance%'
          OR SEARCHABLE_TEXT LIKE '%1.5 percent%'
          OR SEARCHABLE_TEXT LIKE '%1.5%'
        THEN TRUE
        ELSE FALSE
    END AS HAS_LATE_PAYMENT_PENALTY,

    CASE
        WHEN SEARCHABLE_TEXT LIKE '%price increase%'
          OR SEARCHABLE_TEXT LIKE '%advance notice%'
          OR SEARCHABLE_TEXT LIKE '%30 days%'
        THEN TRUE
        ELSE FALSE
    END AS HAS_PRICE_INCREASE_NOTICE

FROM AP_AUTOPILOT.CORE.CONTRACT_SEARCH_VIEW
ORDER BY VENDOR_ID;