USE ROLE ACCOUNTADMIN;
USE WAREHOUSE AP_AUTOPILOT_WH;
USE DATABASE AP_AUTOPILOT;
USE SCHEMA CORE;

CREATE OR REPLACE TABLE CONTRACT_PRICING (
    VENDOR_ID VARCHAR(20),
    LINE_ITEM VARCHAR(200),
    CONTRACT_UNIT_PRICE NUMBER(12, 2),
    SOURCE_FILE VARCHAR(200),
    EXTRACTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);