CREATE OR REPLACE VIEW CONTRACT_STATUS AS
SELECT
    VENDOR_ID,
    VENDOR_NAME,
    CONTRACT_START,
    CONTRACT_END,

    CASE
        WHEN CONTRACT_END IS NULL
            THEN 'MISSING_END_DATE'

        WHEN CONTRACT_END < CURRENT_DATE()
            THEN 'EXPIRED'

        WHEN CONTRACT_END <= DATEADD(
            DAY,
            30,
            CURRENT_DATE()
        )
            THEN 'EXPIRING_SOON'

        ELSE 'ACTIVE'
    END AS CONTRACT_STATUS,

    DATEDIFF(
        DAY,
        CURRENT_DATE(),
        CONTRACT_END
    ) AS DAYS_UNTIL_EXPIRY

FROM AP_AUTOPILOT.CORE.VENDORS;