USE ROLE ACCOUNTADMIN;
USE WAREHOUSE AP_AUTOPILOT_WH;
USE DATABASE AP_AUTOPILOT;
USE SCHEMA AP_AUTOPILOT.CORE;

CREATE OR REPLACE TABLE CONTRACT_CLAUSE_ANALYSIS AS

SELECT

    c.VENDOR_ID,

    c.FILE_NAME,

    s.CONTRACT_STATUS,

    s.DAYS_UNTIL_EXPIRY,

    f.HAS_AUTOMATIC_RENEWAL,

    f.REQUIRES_RENEGOTIATION,

    f.HAS_LATE_PAYMENT_PENALTY,

    f.HAS_PRICE_INCREASE_NOTICE,

    f.HAS_TERMINATION_CLAUSE,

    f.HAS_DISPUTE_CLAUSE,

    CASE

        WHEN s.CONTRACT_STATUS='EXPIRED'
        THEN 'HIGH'

        WHEN f.HAS_LATE_PAYMENT_PENALTY
         AND f.HAS_PRICE_INCREASE_NOTICE
        THEN 'MEDIUM'

        ELSE 'LOW'

    END AS RISK_LEVEL,

    CASE

        WHEN s.CONTRACT_STATUS='EXPIRED'
        THEN 'Contract expired'

        WHEN f.HAS_LATE_PAYMENT_PENALTY
             AND f.HAS_PRICE_INCREASE_NOTICE
        THEN 'Financial clauses require review'

        WHEN f.HAS_AUTOMATIC_RENEWAL
        THEN 'Automatic renewal'

        ELSE 'No major clause risk'

    END AS RISK_REASON,

    CURRENT_TIMESTAMP() AS ANALYSED_AT

FROM AP_AUTOPILOT.CORE.CONTRACT_TEXT c

JOIN CONTRACT_CLAUSE_FLAGS f

ON c.VENDOR_ID=f.VENDOR_ID

JOIN CONTRACT_STATUS s

ON c.VENDOR_ID=s.VENDOR_ID;