USE ROLE ACCOUNTADMIN;
USE WAREHOUSE AP_AUTOPILOT_WH;
USE DATABASE AP_AUTOPILOT;
USE SCHEMA CORE;

CREATE OR REPLACE VIEW EXECUTIVE_AP_DASHBOARD AS

SELECT

COUNT(*) AS TOTAL_INVOICES,

SUM(
CASE
WHEN SEVERITY='HIGH'
THEN 1 ELSE 0 END
) AS HIGH_RISK,

SUM(
CASE
WHEN SEVERITY='LOW'
THEN 1 ELSE 0 END
) AS LOW_RISK,

COUNT(DISTINCT VENDOR_ID) AS VENDORS,

AVG(DIFFERENCE_PERCENT) AS AVG_PRICE_VARIANCE

FROM AP_AUTOPILOT.CORE.INVOICE_ANOMALY_RESULTS;