USE ROLE ACCOUNTADMIN;
USE WAREHOUSE AP_AUTOPILOT_WH;
USE DATABASE AP_AUTOPILOT;
USE SCHEMA CORE;

SELECT COUNT(*) FROM VENDORS;

SELECT COUNT(*) FROM PURCHASE_ORDERS;

SELECT COUNT(*) FROM INVOICES;

SELECT COUNT(*) FROM CONTRACT_TEXT;

SELECT COUNT(*) FROM CONTRACT_PRICING;

SELECT COUNT(*) FROM CONTRACT_CLAUSE_ANALYSIS;

SELECT COUNT(*) FROM INVOICE_ANOMALY_RESULTS;

SELECT COUNT(*) FROM AP_REVIEW_QUEUE;

SELECT COUNT(*) FROM AUDIT_LOG;